#ifndef VECTORSTORM_MATRIX3_FORWARD_H_INCLUDED
#define VECTORSTORM_MATRIX3_FORWARD_H_INCLUDED

#ifdef VMATH_NAMESPACE
namespace VMATH_NAMESPACE {
#endif

template<typename T> class matrix3;

#ifdef VMATH_NAMESPACE
}
#endif //VMATH_NAMESPACE

#include "matrix3_types.h"

#endif // VECTORSTORM_MATRIX3_FORWARD_H_INCLUDED
