#ifndef VECTORSTORM_AABB2_FORWARD_H_INCLUDED
#define VECTORSTORM_AABB2_FORWARD_H_INCLUDED

#ifdef VMATH_NAMESPACE
namespace VMATH_NAMESPACE {
#endif

template<typename T> class aabb2;

#ifdef VMATH_NAMESPACE
}
#endif //VMATH_NAMESPACE

#include "aabb2_types.h"

#endif // VECTORSTORM_AABB2_FORWARD_H_INCLUDED
